FROM ruby:3.2.3

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev tesseract-ocr tesseract-ocr-jpn

# コンテナの作業ディレクトリ
WORKDIR /app

# コンテナの作業ディレクトリにコピー
COPY Gemfile Gemfile.lock /app/

# 依存関係をインストール
RUN bundle install

COPY entrypoint.sh /usr/bin/
# プロジェクト作成時はコメントアウト（コンテナが立ち上がらないため）
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

# プロジェクト作成時はCMDをコメントアウト（コンテナが立ち上がらないため）
CMD ["rails", "server", "-b", "0.0.0.0"]